//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimieTechTv.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessageExceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessageExceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnimieTechTv.Exceptions.ResourceMessageExceptions", typeof(ResourceMessageExceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animie already registered.
        /// </summary>
        public static string ANIMIE_ALREADY_ADDED {
            get {
                return ResourceManager.GetString("ANIMIE_ALREADY_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must not exceed 100 characters.
        /// </summary>
        public static string ANIMIE_CHARACTER {
            get {
                return ResourceManager.GetString("ANIMIE_CHARACTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Director must not exceed 100 characters.
        /// </summary>
        public static string ANIMIE_DIRECTOR_NAME_CHARACTER {
            get {
                return ResourceManager.GetString("ANIMIE_DIRECTOR_NAME_CHARACTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Director is required.
        /// </summary>
        public static string ANIMIE_DIRECTOR_NAME_REQUIRED {
            get {
                return ResourceManager.GetString("ANIMIE_DIRECTOR_NAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Animie ID is required.
        /// </summary>
        public static string ANIMIE_ID_REQUIRED {
            get {
                return ResourceManager.GetString("ANIMIE_ID_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animie name is required.
        /// </summary>
        public static string ANIMIE_NAME_IS_REQUIRED {
            get {
                return ResourceManager.GetString("ANIMIE_NAME_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No animies found with the provided filters.
        /// </summary>
        public static string ANIMIE_NOT_FOUNDED_BY_FILTER {
            get {
                return ResourceManager.GetString("ANIMIE_NOT_FOUNDED_BY_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animie not founded using ID.
        /// </summary>
        public static string ANIMIE_NOT_FOUNDED_BY_ID {
            get {
                return ResourceManager.GetString("ANIMIE_NOT_FOUNDED_BY_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume must not exceed 1000 characters.
        /// </summary>
        public static string ANIMIE_RESUME_CHARACTER {
            get {
                return ResourceManager.GetString("ANIMIE_RESUME_CHARACTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to database.
        /// </summary>
        public static string DATABASE_ERROR {
            get {
                return ResourceManager.GetString("DATABASE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknow error.
        /// </summary>
        public static string UNKNOW_ERROR {
            get {
                return ResourceManager.GetString("UNKNOW_ERROR", resourceCulture);
            }
        }
    }
}
